const bcrypt = require("bcryptjs");
const data = {
  users: [
    {
      name: "ganesh",
      email: "ganeshkalyan506@gmail.com",
      password: bcrypt.hashSync("Ganesh3110#"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Axpro CR7 Studs Shoe",
      slug: "FootBallshoes",
      category: "shoes",
      Image: "/images/cr7Boots.jpg",
      price: 10000,
      rating: "4.8",
      countInStock: 2,
      brand: "Nivia",
      numReviews: 15,
      description:
        "Ankle Length Grip On Shoe Provides Snug Fit And Holds The Ankle Tight Preventing Ankle Injuries,  Pre-Moulded Eva Insole Gives Better Cushioning And Comfort, Molded Heel Counter For Protection And Secure Heel Fit And Also Used Molded Full Plastic Insole For Better Grip And Stability",
    },
    {
      name: "Football Jersey",
      slug: "jersey",
      category: "jersey",
      Image: "/images/cr7jersy.png",
      price: 399,
      rating: "4",
      countInStock: 5,
      brand: "puma",
      numReviews: 19,
      description:
        "Care Instructions: Hand Wash Only,  Fit Type: Regular Fit , Select Correct Size: (7to12 years chest size is 32 inches) & (12to16 years chest size is 36 inches) & Small Chest Size is 36 & Medium Chest Size is 38 & Large Chest Size is 40 & X-Large Chest Size is 42 & XX-Large Chest Size is 44 ,  100% Polyester,Do Not Iron",
    },
    {
      name: "Manchester United Jersey",
      slug: "Manchesterjersey",
      category: "jersey",
      Image: "/images/manchester.jpg",
      price: 369,
      rating: "3.9",
      countInStock: 90,
      brand: "puma",
      numReviews: 20,
      description:
        "Infinity Sports Manchester United Home Football Jersey Ronaldo 7 100% Polyester Do Not Iron",
    },
    {
      name: "Adult Poly Cotton full neck T-shirt",
      slug: "Tshirt",
      category: "T-shirts",
      Image: "/images/cr7Tshirt.jpg",
      price: 1499,
      rating: "4.9",
      countInStock: 10,
      brand: "Nike",
      numReviews: 15,
      description:
        "Fit Type: Regular Fit , Perfect for Winters, Night Highways long drive. Note: Check the Size chart in the product images for perfect fit. , Pattern: Graphic Print, Sleeve type: full sleeve sweatshirts, neck type: hooded sweatshirt, fitting type: regular fit hoodies, occasion: casual.; BRAND : Ebaysic",
    },
    {
      name: "Cr7 T-Shirts",
      slug: "RoundNeck-Tshirt",
      category: "T-shirts",
      Image: "/images/roundneckTshirt.jpg",
      price: 700,
      rating: "4.9",
      countInStock: 10,
      brand: "GUCCI",
      numReviews: 20,
      description:
        "Prink Cristiano Ronaldo Printed T-Shirts | Cr7 T-Shirts for Ronaldo Fans | Football Printed Round Neck Tshirts for Men | Black Cotton Regular fit Tshirts |",
    },
    {
      name: "Sipper Bottle",
      slug: "Bottle",
      category: "waterBottel",
      Image: "/images/SipperBottle.jpg",
      price: 400,
      rating: "2.8",
      countInStock: 19,
      brand: "GUCCI",
      numReviews: 10,
      description:
        "Morons Colorful Cristiano Ronaldo Sipper Bottle | Ronaldo Bottle | Football Sipper Bottle | Printed Sipper Bottle - [600 ml, Multi-Color], Pack of 1, High Quality Material: Take your drinks everywhere with this white aluminum sipper bottle, which is a perfect container to keep your cold beverages, when you are out of your house. It is the perfect companion for your outdoor activities",
    },
    {
      name: "perfume 100ml",
      slug: "perfume",
      category: "perfumes",
      Image: "/images/perfume.jpg",
      price: 3185,
      rating: "5",
      countInStock: 5,
      brand: "cr7",
      numReviews: 10,
      description:
        "Cristiano Ronaldo CR7 Game On Eau de Toilette 100ml ,CRISP APPLE PAPAYA CARDAMOM CRUSHED ICE,ELEMI VIOLET DEW LAVENDER BUD JUNIPER BERRY ,CASHMERE WOODS CEDARWOOD SUGARED TONKA BEAN GUAIACWOOD",
    },
    {
      name: "Leather Wallet",
      slug: "Wallet",
      category: "Leather Wallet",
      Image: "/images/Wallet.png",
      price: 349,
      rating: "4",
      countInStock: 10,
      brand: "lether",
      numReviews: 7,
      description:
        "ShopMantra Cristiano Ronaldo CR7 Printed Pu Leather Wallet for Men's/Boy's (Black) , Slim & Lightweight Size : 11.5 X 2 X 9.5 Cm. Bi-Fold Stylish Design Is Made For You To Keep Your Things Organized Well And Easy To Use.; Material : PU Printed On Upper Side, Inside Premium Leather. Handmade By The Finest Craftsmanship Makes You Feel Luxurious And Comfortable Made In India Product.",
    },
    {
      name: "Rubber Handband",
      slug: "Handband",
      category: "Rubber Handband",
      Image: "/images/handBand.jpg",
      price: 149,
      rating: "3",
      countInStock: 30,
      brand: "lether",
      numReviews: 7,
      description:
        "Desire Collection Cristiano Ronaldo Rubber Handband For Boys Hand Band For Kids ,Boys ,Girls and Men (Black) , Desire Collection Cristiano Ronaldo Rubber Handband For Boys High Quality Hand Band Latest Design For Kids Boys Girls MenSize: freesize; Best Gift to your loved ones",
    },
    {
      name: "CR7 Posters",
      slug: "CR7Posters",
      category: "Posters",
      Image: "/images/cr7.jpg",
      price: 199,
      rating: "4.5",
      countInStock: 0,
      brand: "lether",
      numReviews: 10,
      description:
        "VVWV CR7 Posters Football Players Copa America Inspirational Motivational Home Bedroom Living Room Wall Decoration 300 GSM L X H 12 .00 X 18.00 Inches , High Quality Special Media Xerox Printed Posters",
    },
    {
      name: "CR7 Signature Bracelet",
      slug: "SignatureBracelet",
      category: "Jewelgenics ",
      Image: "/images/cr7Jwel.png",
      price: 299,
      rating: "3",
      countInStock: 0,
      brand: "Jewelgenics",
      numReviews: 4,
      description:
        "Jewelgenics Cristiano Ronaldo CR7 Signature Bracelet - Men's Silicone Adjustable Sports Wristband (Black) , Material: Silicone, Metals Type: Stainless Steel, Chain Type: watchband, Style: Trendy, Clasp Type: Fold Over Clasp, Color: Black, Football player: Cristiano Ronaldo.",
    },
  ],
};
module.exports = data;
